# Generated by Django 4.2 on 2024-02-29 17:03

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blogpost_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, validators=[blog.models.validate_positive], verbose_name='Число')),
                ('title', models.CharField(max_length=255, verbose_name='Тема')),
                ('info', models.TextField(blank=True, verbose_name='Инфо')),
                ('tags', models.ManyToManyField(blank=True, to='blog.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Опыт',
                'verbose_name_plural': 'Опты',
            },
        ),
    ]
